### PR TITLE
Fix ColumnDefinition type

### PR DESCRIPTION
**Pull request by bencmbrook**
Closes https://github.com/markdirish/node-odbc/issues/172

### CODE REVIEW

**Review by markdirish — APPROVED** [review]
LGTM!

**Comment by markdirish** [comment]
Thanks for the PR. In the future I will try to keep the Typescript definitions up to date, it slipped my mind this time.

**Comment by bencmbrook** [comment]
Of course. Thanks for the awesome repo!

Sorry, should I have bumped the package? Not sure what your npm publish workflow is. Would love to update my dependency once published to clean up some of my type overrides 🙂

**Comment by markdirish** [comment]
Nah I have a whole workflow for it. I'm on the tail end of getting a big version update out the door, hopefully soon (I've said for a while). Just finishing up #161 and then hunting down bugs! Hopefully a new version with your changes soon!

**Comment by bencmbrook** [comment]
Okay cool - will stay tuned! Thanks

**Pull request merged**
