### PR TITLE
Add documentation for QueryOptions on .execute

### PR DESCRIPTION
**Pull request by bencmbrook**
Adds documentation for new options parameter on Statement#execute as added in https://github.com/markdirish/node-odbc/pull/236 (issue https://github.com/markdirish/node-odbc/issues/228)

### CODE REVIEW

**Comment by bencmbrook** [comment]
@markdirish regarding the DCO check, let me know if you want me to use the `-s` and push (not sure if that's intended to be "signed off by" a repo owner rather than an external contributor...)

**Comment by kadler** [comment]
The DCO bot is asking _you_ to sign off. Since (presumably) you are the copyright owner to the changes being made, only you can do the sign off.

**Comment by bencmbrook** [comment]
@kadler gotcha. Done!

**Comment by bencmbrook** [comment]
closing in favor of #278

**Pull request closed without merging**
