### PR TITLE
Update Pool.js

### PR DESCRIPTION
**Pull request by hellower**
missing "let"

### CODE REVIEW

**Review by kadler — APPROVED** [review]
LGTM.

@mirish seems trivial enough to not require DCO.

**Comment by markdirish** [comment]
For whatever reason, I can't bring myself to pull the trigger without the DCO.

@hellower , would you mind following the instruction here? https://github.com/markdirish/node-odbc/pull/207/checks?check_run_id=3120653206

It will "sign-off" the commit saying that it is your own work and you have the authority to give it to us, and that you understand we will use it in the package.

**Comment by hellower** [comment]
[root@tnt-factory:/tmp/node-odbc/lib]
__STAGE__# git push --force-with-lease origin patch-1
error: src refspec patch-1 does not match any.
error: failed to push some refs to 'https://github.com/markdirish/node-odbc.git'
[root@tnt-factory:/tmp/node-odbc/lib]

I'm not familiar with git, so I get an error. I don't know how to fix .

Just close this and fix it yourself, please
Thanks!

**Comment by kadler** [comment]
@hellower Based on the branch name, this looks like it was edited online. I think you cloned Mark's repo instead of your fork, so it's trying to push to the wrong location.

You can change the URL like so: `git remote set-url origin git@github.com:hellower/node-odbc.git` (or `git remote set-url origin https://github.com/hellower/node-odbc.git` if you haven't set up SSH keys and want to use HTTP authentication).

**Comment by hellower** [comment]
> @hellower Based on the branch name, this looks like it was edited online. I think you cloned Mark's repo instead of your fork, so it's trying to push to the wrong location.
> 
> You can change the URL like so: `git remote set-url origin git@github.com:hellower/node-odbc.git` (or `git remote set-url origin https://github.com/hellower/node-odbc.git` if you haven't set up SSH keys and want to use HTTP authentication).

Thanks for the kind  guide.

**Comment by markdirish** [comment]
Thanks for the PR!

**Pull request merged**
